In [1]:
# Import required system
import sys
sys.path.append('/Users/hoto7260/LIET/Jacob_LIET2/LIET/liet')
sys.path.append('/Users/hoto7260/LIET/Hope_Graphing_LIET/functions')

# general
import matplotlib.pyplot as plt
import numpy as np
try:
    np.distutils.__config__.blas_opt_info = np.distutils.__config__.blas_ilp64_opt_info
except Exception:
    pass
import pandas as pd
from scipy.stats import pearsonr
import plotly.express as px

# my modules
from liet_res_class import FitParse
import rnap_lib_data_proc  as dp
import plotting_funcs as pf
import analysis_funcs as af

# setting plotting paramaters
from pylab import rcParams
rcParams['figure.figsize'] = 20, 6
rcParams['font.size'] = 15
#plt.rcParams.update({'font.size': 22})

/tmp/ipykernel_357497/1732951080.py:13: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [21]:
# for each gene, get the proper locations
def get_LIET_end_results(LIET_df, endtype = "0.9_perc"):
    """
    Parameters
    ----------
    LIET_df: the LIET df output by FitParse in plotting_functions.py
    end_type: str
        - either EMG, Full, or another string (string must be a column in the dataframe)
        IN ALL CASES assumes the positive strand is the sense strand
    This function adds additional BID specific related elements to the dataframe: calculates the end positions for both strands.
    in: pandas Dataframe from the FitParse dataframe class with the sL, tI, and start information
    out: pandas DataFrame with the following ADDITIONAL columns (one row per bidirectional):
        * rel_pos_end = sL_mean + tI_mean
        * rel_pos_end_interval = (sL_mean - sL_stdev)+(tI_mean - tI_stdev),(sL_mean + sL_stdev)+(tI_mean + tI_stdev)
        * abs_pos_end = start + sL_mean + tI_mean
        * abs_pos_end_interval = start+[(sL_mean - sL_stdev)+(tI_mean - tI_stdev)],start+[(sL_mean + sL_stdev)+(tI_mean + tI_stdev)]
        * rel_neg_end = sL_a_mean + tI_a_mean
        * rel_neg_end_interval = (sL_a_mean - sL_a_stdev)+(tI_a_mean - tI_a_stdev),(sL_a_mean + sL_a_stdev)+(tI_a_mean + tI_a_stdev)
        * abs_neg_end = mu - sL_a_mean - tI_a_mean
        * abs_neg_end_interval = start+[(sL_a_mean - sL_a_stdev)+(tI_a_mean - tI_a_stdev)],start+[(sL_a_mean + sL_a_stdev)+(tI_a_mean + tI_a_stdev)]
    """
    # if mT then use that
    if endtype == "mT":
        # Positive
        LIET_df = LIET_df.assign(rel_pos_end = LIET_df["mT_mean"].astype(int)) 
        LIET_df = LIET_df.assign(abs_pos_end = LIET_df["start"]+LIET_df["mT_mean"].astype(int))
        LIET_df = LIET_df.assign(rel_neg_end = LIET_df["mT_a_mean"].astype(int)) 
        LIET_df = LIET_df.assign(abs_neg_end = LIET_df["start"]-LIET_df["mT_a_mean"].astype(int))
    else:
        # SENSE STRAND
        pos_end = "_".join([endtype, "pos"])
        LIET_df = LIET_df.assign(rel_pos_end = LIET_df[pos_end]) 
        LIET_df = LIET_df.assign(abs_pos_end = LIET_df["start"]+LIET_df[pos_end])
        # negative strand in my case
        neg_end = "_".join([endtype, "neg"])
        LIET_df = LIET_df.assign(rel_neg_end = LIET_df[neg_end]) 
        LIET_df = LIET_df.assign(abs_neg_end = LIET_df["start"]-LIET_df[neg_end])
    return LIET_df


def get_LIET_end_bed(LIET_df, end_type, antisense=True):
    """
    This function transforms the FitParse dataframe of bidirectionals into a bed file where the start position
    refers to the 3' most end of the - transcript and end to the 3' most end of the + transcript 
    (midpoint is NOT mu). Mu is saved as a separate column. The df also contains additional
    information that might be helpful for downstream analysis or evaluating the trustworthiness of the results.
    in: pandas Dataframe from the FitParse dataframe class that has undergone the get_LIET_end_results function.
    out: pandas DataFrame with the following columns (one row per bidirectional):
        * chr
        * start = most upstream (3' end of - strand)
        * end = most downstream (3' end of + strand)
        * name = name with |- or |+ according to strand
        * wLI_mean = w_LI_mean,w_aLI_mean
        * coverage = pos_cov,neg_cov
        * LI_coverage = coverage attributable to NOT background
        * rel_end_stdev = rel_pos_end_stdev,rel_neg_end_stdev
        * mu
        * elbo_lrange
    """
    if end_type == "EMG":
        LI_pos_cov = LIET_df["pos_cov"]*LIET_df["w_LI_mean"]
        rel_pos_end_stdev = LIET_df["sL_stdev"]+LIET_df["tI_stdev"]
        if antisense:
            LI_neg_cov = LIET_df["neg_cov"]*LIET_df["w_aLI_mean"]
            rel_neg_end_stdev = LIET_df["sL_a_stdev"]+LIET_df["tI_a_stdev"]
        else:
            LI_neg_cov = ["NA"]*len(LIET_df.chrom)
            rel_neg_end_stdev = ["NA"]*len(LIET_df.chrom)
        bed = pd.DataFrame({"chr": LIET_df.chrom, 
                               "start": LIET_df.start+LIET_df.mL_mean.astype(int), "end": LIET_df.abs_pos_end.astype(int), 
                              "name": LIET_df["gene"] , 
                              "wLI_mean": LIET_df["w_LI_mean"].astype(str)+","+LIET_df["w_aLI_mean"].astype(str),
                            "coverage": LIET_df["pos_cov"].astype(str)+","+LIET_df["neg_cov"].astype(str), 
                            "LI_coverage": LI_pos_cov.astype(int).astype(str)+","+LI_neg_cov.astype(int).astype(str),
                               "rel_end_stdev": rel_pos_end_stdev.round(1).astype(str)+","+rel_neg_end_stdev.round(1).astype(str), 
                           "mu":LIET_df.start, "elbow_lrange": LIET_df.elbo_lrange})
    else:
        if antisense:
            print("Not available rn")
        else:
            if end_type == "Full":
                rel_end_stdev=LIET_df["mT_stdev"].round(1).astype(str)
            else:
                rel_end_stdev= ["NA"]*len(LIET_df.chrom)
            non_wB_mean = 1 - LIET_df["w_B_mean"]
            LIE_pos_cov = LIET_df["pos_cov"]*non_wB_mean
            bed = pd.DataFrame({"chr": LIET_df.chrom, 
                                   "start": LIET_df.start+LIET_df.mL_mean.astype(int), "end": LIET_df.abs_pos_end.astype(int), 
                                  "name":  LIET_df["gene"]+"|+" , 
                                "LIET_coverage": LIE_pos_cov.astype(int),
                                "strand": ["+"]*LIET_df.shape[0],
                                "coverage": LIET_df["pos_cov"].astype(str), 
                                  "wLIET_mean": non_wB_mean.round(3),
                                "filler": ["."]*LIET_df.shape[0],
                                   "rel_end_stdev": rel_end_stdev, 
                               "mu":LIET_df.start, "elbow_lrange": LIET_df.elbo_lrange})
        
    return bed

def get_LIET_end_sep_bed(LIET_df, ET_sense=True, antisense=True, ET_antisense=False):
    """
    This function transforms the FitParse dataframe of bidirectionals into a bed file where the start position
    refers to the 3' most end of the - transcript and end to the 3' most end of the + transcript 
    (midpoint is NOT mu). Mu is saved as a separate column. The df also contains additional
    information that might be helpful for downstream analysis or evaluating the trustworthiness of the results.
    in: pandas Dataframe from the FitParse dataframe class that has undergone the get_LIET_end_results function.
    out: pandas DataFrame with the following columns (two rows per bidirectional):
        * chr
        * start = most upstream (3' end of - strand & 5' end of + strand)
        * end = most downstream (3' end of + strand & 5' end of - strand)
        * name = name with |- or |+ according to strand
        * wLI_mean = w_LI_mean or w_aLI_mean
        * coverage = pos_cov or neg_cov
        * LI_coverage = coverage attributable to NOT background
        * rel_end_stdev = rel_pos_end_stdev or rel_neg_end_stdev
        * mu
        * elbo_lrange (same for both strands)
    """
    # get the postive strand bed
    if ET_sense:
        w_LIET = 1-LIET_df["w_B_mean"]
        LIET_pos_cov = LIET_df["pos_cov"]*w_LIET
        pos_bed = pd.DataFrame({"chr": LIET_df.chrom, 
                               "start": LIET_df.start+LIET_df.mL_mean.astype(int), "end": LIET_df.abs_pos_end.astype(int), 
                              "name": LIET_df["gene"]+"|+" , 
                                "LIET_coverage": LIET_pos_cov.astype(int),
                                "strand": ["+"]*LIET_df.shape[0],
                            "coverage": LIET_df["pos_cov"], 
                                "wLIET_mean": w_LIET.round(3),
                                "filler": ["."]*LIET_df.shape[0],
                           "mu":LIET_df.start, "elbow_lrange": LIET_df.elbo_lrange})
    else:
        LI_pos_cov = LIET_df["pos_cov"]*LIET_df["w_LI_mean"]
        pos_bed = pd.DataFrame({"chr": LIET_df.chrom, 
                               "start": LIET_df.start+LIET_df.mL_mean.astype(int), "end": LIET_df.abs_pos_end.astype(int), 
                              "name": LIET_df["gene"]+"|+" , 
                                "LI_coverage": LI_pos_cov.astype(int),
                                "strand": ["+"]*LIET_df.shape[0],
                            "coverage": LIET_df["pos_cov"], 
                                "wLI_mean": LIET_df["w_LI_mean"].round(3),
                                "filler": ["."]*LIET_df.shape[0],
                           "mu":LIET_df.start, "elbow_lrange": LIET_df.elbo_lrange})
    # get the negative strand bed
    if ET_antisense:
        w_a_LIET = 1-LIET_df["w_aB_mean"]
        LIET_neg_cov = LIET_df["neg_cov"]*w_a_LIET
        neg_bed = pd.DataFrame({"chr": LIET_df.chrom, 
                               "start": LIET_df.abs_neg_end.astype(int), "end": LIET_df.start - LIET_df.mL_a_mean.astype(int), 
                              "name": LIET_df["gene"]+"|-" , 
                                "LIET_coverage": LIET_neg_cov.astype(int),
                                "strand": ["-"]*LIET_df.shape[0],
                            "coverage": LIET_df["neg_cov"], 
                                "wLIET_mean": w_a_LIET.round(3),
                                "filler": ["."]*LIET_df.shape[0],
                           "mu":LIET_df.start, "elbow_lrange": LIET_df.elbo_lrange})
    else:
        
        LI_neg_cov = LIET_df["neg_cov"]*LIET_df["w_aLI_mean"]
        neg_bed = pd.DataFrame({"chr": LIET_df.chrom, 
                               "start": LIET_df.abs_neg_end.astype(int), "end": LIET_df.start - LIET_df.mL_a_mean.astype(int), 
                              "name": LIET_df["gene"]+"|-" , 
                              "LI_coverage": LI_neg_cov.astype(int),
                                "strand": ["-"]*LIET_df.shape[0],
                            "coverage": LIET_df["neg_cov"], 
                                "wLI_mean": LIET_df["w_aLI_mean"].round(3),
                                "filler": ["."]*LIET_df.shape[0],
                           "mu":LIET_df.start, "elbow_lrange": LIET_df.elbo_lrange})
    # combine the two
    return pd.concat([pos_bed, neg_bed])

## Save the stranded bed files 
* To use other percentiles, change "0.95_perc" to "0.85_perc", etc.
* To use mT values, change "0.95_perc" to "mT". **Using mT requires that you ran the full model**

**Colon_Format Option**
* People often name enhancers according to chromomsome and positions separated by a colon. Many parameters are also separated by a colon in the results file. To address this, if you named your regions with a colon included, have colon_format=True otherwise you will get an error.

In [50]:
prefixes = ["sm36-ALI-D21_120UPM-1_EMG", "sm36-ALI-D21_120UPM-2_EMG", 
           "sm36-ALI-D21_30UPM-1_EMG", "sm36-ALI-D21_30UPM-2_EMG", 
           "sm36-ALI-D21_veh-1_EMG", "sm36-ALI-D21_veh-2_EMG"]

prefixes = ["sm36-ALI-D21_30UPM-2_EMG", "SRR13772353_EMG"]
bed_dir="/scratch/Users/hoto7260/Resp_Env/Comb_UPM_WSP_ADP/LIET/LIET/LIET_results/beds"
from pathlib import Path

In [51]:
# save dataframe results in a dictionary
df_dict = dict()
for prefix in prefixes:
    print(prefix)
    ## Original files
    log_file = out_dir+prefix+"/"+prefix+".liet.log"
    res_file = out_dir+prefix+"/"+prefix+".liet"
    results = FitParse(res_file=res_file, log_file=log_file, antisense=True, 
                                     ET_sense=False, ET_antisense=False, colon_format=True)
    ends = get_LIET_end_results(results.df, endtype = "0.95_perc")
    bed = get_LIET_end_sep_bed(ends, ET_sense=False, antisense=True, ET_antisense=False)

    ## Now error files (only if they exist)
    log_file = out_dir+prefix+"_err/"+prefix+".liet.log"
    res_file = out_dir+prefix+"_err/"+prefix+".liet"
    if Path(res_file).is_file():
        err_results = FitParse(res_file=res_file, log_file=log_file, antisense=True, 
                                         ET_sense=False, ET_antisense=False, colon_format=True)
        ends = get_LIET_end_results(err_results.df, endtype = "0.95_perc")
        err_bed = get_LIET_end_sep_bed(ends, ET_sense=False, antisense=True, ET_antisense=False)
        # combine
        full_bed = pd.concat([bed, err_bed])
        full_results_df = pd.concat([results.df, err_results.df])
    else:
        full_bed = bed
        full_results_df = results.df
    df_dict[prefix] = full_results_df
    full_bed.to_csv("".join([prefix, "_95p.liet.bed"]), 
                sep="\t", header=False, index=False)

sm36-ALI-D21_30UPM-2_EMG

CHECK LINE: ['chr13:105981024: fitting error']
CHECK LINE: ['chr13:109213060: model error']
CHECK LINE: ['chr13:109647311: model error']
CHECK LINE: ['chr13:110012222: model error']
CHECK LINE: ['chr13:110715565: model error']
CHECK LINE: ['chr14:22614289: fitting error']
CHECK LINE: ['chr14:24274334: model error']
CHECK LINE: ['chr14:32078045: model error']
CHECK LINE: ['chr14:35365599: fitting error']
CHECK LINE: ['chr14:36856477: model error']
CHECK LINE: ['chr14:37571271: model error']
CHECK LINE: ['chr14:38808927: model error']
CHECK LINE: ['chr14:51479947: model error']
CHECK LINE: ['chr14:55339862: model error']
CHECK LINE: ['chr14:68527525: model error']
CHECK LINE: ['chr14:69658124: fitting error']
CHECK LINE: ['chr14:70707402: model error']
CHECK LINE: ['chr14:75868193: model error']
CHECK LINE: ['chr14:77981073: model error']
CHECK LINE: ['chr14:81401428: fitting error']
CHECK LINE: ['chr14:90513810: fitting error']
CHECK LINE: ['chr14:94396118: fitting error']
CHECK LINE: ['chr14:95291335: model error']
CHECK LINE: ['chr14:96362219: model error']
CHECK LINE: ['chr14:100214610: fitting error']
CHECK LINE: ['chr14:102088252: model error']
CHECK LINE: ['chr14:104104886: fitting error']
CHECK LINE: ['chr15:30045888: fitting error']
CHECK LINE: ['chr15:37921832: model error']
CHECK LINE: ['chr15:41806622: fitting error']
CHECK LINE: ['chr15:45058840: fitting error']
CHECK LINE: ['chr15:48963320: model error']
CHECK LINE: ['chr15:55341230: fitting error']
CHECK LINE: ['chr15:58441124: model error']
CHECK LINE: ['chr15:60408654: fitting error']
CHECK LINE: ['chr15:62113191: model error']
CHECK LINE: ['chr15:64355577: model error']
CHECK LINE: ['chr15:65638462: model error']
CHECK LINE: ['chr15:67106962: model error']
CHECK LINE: ['chr15:68272096: model error']
CHECK LINE: ['chr15:70493005: fitting error']
CHECK LINE: ['chr15:74218274: fitting error']
CHECK LINE: ['chr15:74654371: model error']
CHECK LINE: ['chr15:75176557: model error']
CHECK LINE: ['chr15:75578828: model error']
CHECK LINE: ['chr15:77160652: model error']
CHECK LINE: ['chr15:80151256: model error']
CHECK LINE: ['chr15:82373887: model error']
CHECK LINE: ['chr15:82951976: model error']
CHECK LINE: ['chr15:85177250: model error']
CHECK LINE: ['chr15:89880982: fitting error']
CHECK LINE: ['chr15:91943112: model error']
CHECK LINE: ['chr15:92810738: fitting error']
CHECK LINE: ['chr15:93829667: model error']
CHECK LINE: ['chr15:98727750: fitting error']
CHECK LINE: ['chr15:100693683: fitting error']
CHECK LINE: ['chr15:100727445: model error']
CHECK LINE: ['chr16:71590: fitting error']
CHECK LINE: ['chr16:401542: fitting error']
CHECK LINE: ['chr16:2430530: fitting error']
CHECK LINE: ['chr16:3457641: fitting error']
CHECK LINE: ['chr16:4976320: fitting error']
CHECK LINE: ['chr16:11635547: model error']
CHECK LINE: ['chr16:14634022: model error']
CHECK LINE: ['chr16:23145170: fitting error']
CHECK LINE: ['chr16:27318104: model error']
CHECK LINE: ['chr16:27625486: model error']
CHECK LINE: ['chr16:28925608: fitting error']
CHECK LINE: ['chr16:30065120: fitting error']
CHECK LINE: ['chr16:30634425: fitting error']
CHECK LINE: ['chr16:53094378: model error']
CHECK LINE: ['chr16:54484716: fitting error']
CHECK LINE: ['chr16:67160976: model error']
CHECK LINE: ['chr16:68434947: model error']
CHECK LINE: ['chr16:71484359: fitting error']
CHECK LINE: ['chr16:78684492: model error']
CHECK LINE: ['chr16:80027397: fitting error']
CHECK LINE: ['chr16:81447787: model error']
CHECK LINE: ['chr16:81584307: fitting error']
CHECK LINE: ['chr16:84356727: model error']
CHECK LINE: ['chr16:85525190: fitting error']
CHECK LINE: ['chr16:85750328: model error']
CHECK LINE: ['chr16:87945686: model error']
CHECK LINE: ['chr16:88784574: model error']
CHECK LINE: ['chr17:881051: fitting error']
CHECK LINE: ['chr17:1087896: fitting error']
CHECK LINE: ['chr17:1580408: model error']
CHECK LINE: ['chr17:2393917: fitting error']
CHECK LINE: ['chr17:3004948: model error']
CHECK LINE: ['chr17:4854476: model error']
CHECK LINE: ['chr17:14187780: model error']
CHECK LINE: ['chr17:14741720: fitting error']
CHECK LINE: ['chr17:16215083: model error']
CHECK LINE: ['chr17:17028312: fitting error']
CHECK LINE: ['chr17:17729073: model error']
CHECK LINE: ['chr17:18184747: model error']
CHECK LINE: ['chr17:19867145: model error']
CHECK LINE: ['chr17:20952447: model error']
CHECK LINE: ['chr17:27474118: fitting error']
CHECK LINE: ['chr17:27526800: fitting error']
CHECK LINE: ['chr17:29149565: model error']
CHECK LINE: ['chr17:30364048: model error']
CHECK LINE: ['chr17:30601402: model error']
CHECK LINE: ['chr17:31805732: model error']
CHECK LINE: ['chr17:34252579: fitting error']
CHECK LINE: ['chr17:37710628: fitting error']
CHECK LINE: ['chr17:38703916: model error']
CHECK LINE: ['chr17:39701669: model error']
CHECK LINE: ['chr17:40123268: model error']
CHECK LINE: ['chr17:40551427: model error']
CHECK LINE: ['chr17:41301623: fitting error']
CHECK LINE: ['chr17:41544793: model error']
CHECK LINE: ['chr17:41667982: fitting error']
CHECK LINE: ['chr17:42678241: fitting error']
CHECK LINE: ['chr17:43339486: fitting error']
CHECK LINE: ['chr17:45173053: fitting error']
CHECK LINE: ['chr17:45493882: model error']
CHECK LINE: ['chr17:47502204: fitting error']
CHECK LINE: ['chr17:48100878: model error']
CHECK LINE: ['chr17:49993579: model error']
CHECK LINE: ['chr17:50290202: fitting error']
CHECK LINE: ['chr17:50884131: model error']
CHECK LINE: ['chr17:58006612: model error']
CHECK LINE: ['chr17:59858265: fitting error']
CHECK LINE: ['chr17:62653300: model error']
CHECK LINE: ['chr17:63621830: model error']
CHECK LINE: ['chr17:64385509: fitting error']
CHECK LINE: ['chr17:64834524: fitting error']
CHECK LINE: ['chr17:67365741: fitting error']
CHECK LINE: ['chr17:72299748: fitting error']
CHECK LINE: ['chr17:72589422: model error']
CHECK LINE: ['chr17:72717448: fitting error']
CHECK LINE: ['chr17:73455448: fitting error']
CHECK LINE: ['chr17:74443059: model error']
CHECK LINE: ['chr17:75182600: model error']
CHECK LINE: ['chr17:75786414: model error']
CHECK LINE: ['chr17:76500742: model error']
CHECK LINE: ['chr17:77145938: model error']
CHECK LINE: ['chr17:77392844: fitting error']
CHECK LINE: ['chr17:78142094: fitting error']
CHECK LINE: ['chr17:78384180: fitting error']
CHECK LINE: ['chr17:78883554: fitting error']
CHECK LINE: ['chr17:80454803: model error']
CHECK LINE: ['chr17:81329728: model error']
CHECK LINE: ['chr17:81387127: fitting error']
CHECK LINE: ['chr17:81916767: model error']
CHECK LINE: ['chr17:82848281: fitting error']
CHECK LINE: ['chr18:3595018: model error']
CHECK LINE: ['chr18:7941664: fitting error']
CHECK LINE: ['chr18:9649163: model error']
CHECK LINE: ['chr18:11831528: model error']
CHECK LINE: ['chr18:12288192: model error']
CHECK LINE: ['chr18:21741331: model error']
CHECK LINE: ['chr18:22678774: fitting error']
CHECK LINE: ['chr18:23574215: fitting error']
CHECK LINE: ['chr18:26656562: model error']
CHECK LINE: ['chr18:31500337: model error']
CHECK LINE: ['chr18:32372847: model error']
CHECK LINE: ['chr18:36672462: model error']
CHECK LINE: ['chr18:48949977: fitting error']
CHECK LINE: ['chr18:50286739: model error']
CHECK LINE: ['chr18:54254471: model error']
CHECK LINE: ['chr18:55779778: model error']
CHECK LINE: ['chr18:58263164: model error']
CHECK LINE: ['chr18:62329889: fitting error']
CHECK LINE: ['chr18:63041091: fitting error']
CHECK LINE: ['chr18:63553351: model error']
CHECK LINE: ['chr18:63882914: model error']
CHECK LINE: ['chr18:74288999: model error']
CHECK LINE: ['chr18:74951293: model error']
CHECK LINE: ['chr18:77068538: model error']
CHECK LINE: ['chr19:573474: model error']
CHECK LINE: ['chr19:1748310: model error']
CHECK LINE: ['chr19:2087434: model error']
CHECK LINE: ['chr19:2540921: fitting error']
CHECK LINE: ['chr19:3055278: model error']
CHECK LINE: ['chr19:3368395: model error']
CHECK LINE: ['chr19:4009387: model error']
CHECK LINE: ['chr19:4376386: fitting error']
CHECK LINE: ['chr19:5166224: fitting error']
CHECK LINE: ['chr19:6108906: model error']
CHECK LINE: ['chr19:7198311: model error']
CHECK LINE: ['chr19:9008790: model error']
CHECK LINE: ['chr19:9054821: model error']
CHECK LINE: ['chr19:10402675: model error']
CHECK LINE: ['chr19:11143378: fitting error']
CHECK LINE: ['chr19:11815378: fitting error']
CHECK LINE: ['chr19:12782714: fitting error']
CHECK LINE: ['chr19:14497712: model error']
CHECK LINE: ['chr19:14537473: fitting error']
CHECK LINE: ['chr19:16161239: model error']
CHECK LINE: ['chr19:17247327: model error']
CHECK LINE: ['chr19:18021504: model error']
CHECK LINE: ['chr19:18157262: model error']
CHECK LINE: ['chr19:18341283: model error']
CHECK LINE: ['chr19:18764083: fitting error']
CHECK LINE: ['chr19:19591577: model error']
CHECK LINE: ['chr19:21596464: model error']
CHECK LINE: ['chr19:32692315: fitting error']
CHECK LINE: ['chr19:35716616: fitting error']
CHECK LINE: ['chr19:36771741: fitting error']
CHECK LINE: ['chr19:37978252: model error']
CHECK LINE: ['chr19:38698948: model error']
CHECK LINE: ['chr19:39195921: model error']
CHECK LINE: ['chr19:40365786: model error']
CHECK LINE: ['chr19:40613959: fitting error']
CHECK LINE: ['chr19:41220521: model error']
CHECK LINE: ['chr19:41749489: model error']
CHECK LINE: ['chr19:42049310: model error']
CHECK LINE: ['chr19:43202162: model error']
CHECK LINE: ['chr19:43798854: model error']
CHECK LINE: ['chr19:44890614: fitting error']
CHECK LINE: ['chr19:45729904: model error']
CHECK LINE: ['chr19:46731318: model error']
CHECK LINE: ['chr19:47606382: model error']
CHECK LINE: ['chr19:48334677: model error']
CHECK LINE: ['chr19:48568606: model error']
CHECK LINE: ['chr19:50167987: fitting error']
CHECK LINE: ['chr19:51017143: model error']
CHECK LINE: ['chr19:52897328: model error']
CHECK LINE: ['chr19:53981000: model error']
CHECK LINE: ['chr19:56217469: model error']
CHECK LINE: ['chr2:1743251: model error']
CHECK LINE: ['chr2:9212473: model error']
CHECK LINE: ['chr2:9476754: model error']
CHECK LINE: ['chr2:9952949: fitting error']
CHECK LINE: ['chr2:10812061: model error']
CHECK LINE: ['chr2:12588331: model error']
CHECK LINE: ['chr2:17588176: model error']
CHECK LINE: ['chr2:20114121: model error']
CHECK LINE: ['chr2:20185727: model error']
CHECK LINE: ['chr2:20438632: fitting error']
CHECK LINE: ['chr2:20822230: model error']
CHECK LINE: ['chr2:25340636: model error']
CHECK LINE: ['chr2:26003134: model error']
CHECK LINE: ['chr2:27085857: model error']
CHECK LINE: ['chr2:28338810: model error']
CHECK LINE: ['chr2:28661990: model error']
CHECK LINE: ['chr2:31430950: model error']
CHECK LINE: ['chr2:33211512: model error']
CHECK LINE: ['chr2:36597900: model error']
CHECK LINE: ['chr2:38075059: fitting error']
CHECK LINE: ['chr2:38109626: fitting error']
CHECK LINE: ['chr2:38447347: model error']
CHECK LINE: ['chr2:39495097: model error']
CHECK LINE: ['chr2:42562644: model error']
CHECK LINE: ['chr2:43219959: model error']
CHECK LINE: ['chr2:45169951: model error']
CHECK LINE: ['chr2:46914246: fitting error']
CHECK LINE: ['chr2:55616909: fitting error']
CHECK LINE: ['chr2:62307863: fitting error']
CHECK LINE: ['chr2:64204285: fitting error']
CHECK LINE: ['chr2:64750142: model error']
CHECK LINE: ['chr2:65309769: model error']
CHECK LINE: ['chr2:69046431: model error']
CHECK LINE: ['chr2:69763312: model error']
CHECK LINE: ['chr2:70403676: model error']
CHECK LINE: ['chr2:84946574: fitting error']
CHECK LINE: ['chr2:85710827: fitting error']
CHECK LINE: ['chr2:86622603: fitting error']
CHECK LINE: ['chr2:95310638: model error']
CHECK LINE: ['chr2:96502015: fitting error']
CHECK LINE: ['chr2:97869607: model error']
CHECK LINE: ['chr2:99470861: model error']
CHECK LINE: ['chr2:101234347: fitting error']
CHECK LINE: ['chr2:101766921: fitting error']
CHECK LINE: ['chr2:105426074: fitting error']
CHECK LINE: ['chr2:111641086: model error']
CHECK LINE: ['chr2:111671627: model error']
CHECK LINE: ['chr2:112692662: fitting error']
CHECK LINE: ['chr2:113240390: model error']
CHECK LINE: ['chr2:118125866: model error']
CHECK LINE: ['chr2:119050441: model error']
CHECK LINE: ['chr2:120613132: model error']
CHECK LINE: ['chr2:121505467: model error']
CHECK LINE: ['chr2:130372650: fitting error']
CHECK LINE: ['chr2:130837622: model error']
CHECK LINE: ['chr2:135053184: model error']
CHECK LINE: ['chr2:145496240: fitting error']
CHECK LINE: ['chr2:150485443: model error']
CHECK LINE: ['chr2:151948175: model error']
CHECK LINE: ['chr2:156083866: model error']
CHECK LINE: ['chr2:156342564: fitting error']
CHECK LINE: ['chr2:159140618: model error']
CHECK LINE: ['chr2:160205677: fitting error']
CHECK LINE: ['chr2:160270578: model error']
CHECK LINE: ['chr2:164859488: model error']
CHECK LINE: ['chr2:169036941: model error']
CHECK LINE: ['chr2:170744775: model error']
CHECK LINE: ['chr2:177268925: model error']
CHECK LINE: ['chr2:186772285: model error']
CHECK LINE: ['chr2:190954886: model error']
CHECK LINE: ['chr2:196292261: model error']
CHECK LINE: ['chr2:200259576: model error']
CHECK LINE: ['chr2:200741656: fitting error']
CHECK LINE: ['chr2:201125800: model error']
CHECK LINE: ['chr2:202783374: model error']
CHECK LINE: ['chr2:205685471: model error']
CHECK LINE: ['chr2:207514078: model error']
CHECK LINE: ['chr2:215106250: model error']
CHECK LINE: ['chr2:215982790: model error']
CHECK LINE: ['chr2:216636775: model error']
CHECK LINE: ['chr2:217684558: model error']
CHECK LINE: ['chr2:217988313: model error']
CHECK LINE: ['chr2:218731754: fitting error']
CHECK LINE: ['chr2:219570610: model error']
CHECK LINE: ['chr2:220199116: model error']
CHECK LINE: ['chr2:220334361: model error']
CHECK LINE: ['chr2:220790120: model error']
CHECK LINE: ['chr2:222586578: model error']
CHECK LINE: ['chr2:224585617: model error']
CHECK LINE: ['chr2:227853894: model error']
CHECK LINE: ['chr2:230794131: model error']
CHECK LINE: ['chr2:234983990: fitting error']
CHECK LINE: ['chr2:235495210: model error']
CHECK LINE: ['chr2:236745929: fitting error']
CHECK LINE: ['chr2:237502852: model error']
CHECK LINE: ['chr2:238234546: model error']
CHECK LINE: ['chr2:240568200: model error']
CHECK LINE: ['chr2:241374758: model error']
CHECK LINE: ['chr20:2470194: model error']
CHECK LINE: ['chr20:10540860: model error']
CHECK LINE: ['chr20:10790278: model error']
CHECK LINE: ['chr20:16530319: model error']
CHECK LINE: ['chr20:19880692: model error']
CHECK LINE: ['chr20:22582270: model error']
CHECK LINE: ['chr20:23097081: fitting error']
CHECK LINE: ['chr20:25865839: model error']
CHECK LINE: ['chr20:31719465: model error']
CHECK LINE: ['chr20:32475461: model error']
CHECK LINE: ['chr20:33372470: fitting error']
CHECK LINE: ['chr20:35741627: model error']
CHECK LINE: ['chr20:37541805: fitting error']
CHECK LINE: ['chr20:38980117: fitting error']
CHECK LINE: ['chr20:41693064: model error']
CHECK LINE: ['chr20:45419651: fitting error']
CHECK LINE: ['chr20:45971251: model error']
CHECK LINE: ['chr20:46990669: model error']
CHECK LINE: ['chr20:49768644: model error']
CHECK LINE: ['chr20:50377017: model error']
CHECK LINE: ['chr20:50725054: model error']
CHECK LINE: ['chr20:51481590: model error']
CHECK LINE: ['chr20:51750440: model error']
CHECK LINE: ['chr20:52048062: model error']
CHECK LINE: ['chr20:53504211: model error']
CHECK LINE: ['chr20:53901137: model error']
CHECK LINE: ['chr20:57323124: fitting error']
CHECK LINE: ['chr20:59831222: fitting error']
CHECK LINE: ['chr20:62502050: fitting error']
CHECK LINE: ['chr20:63538905: model error']
CHECK LINE: ['chr20:63911361: fitting error']
CHECK LINE: ['chr21:28699773: fitting error']
CHECK LINE: ['chr21:32348793: model error']
CHECK LINE: ['chr21:32611615: model error']
CHECK LINE: ['chr21:33948839: model error']
CHECK LINE: ['chr21:34692351: model error']
CHECK LINE: ['chr21:36320591: model error']
CHECK LINE: ['chr21:36910151: model error']
CHECK LINE: ['chr21:38913189: model error']
CHECK LINE: ['chr21:39082856: fitting error']
CHECK LINE: ['chr21:41113353: model error']
CHECK LINE: ['chr21:41711815: fitting error']
CHECK LINE: ['chr21:42234830: fitting error']
CHECK LINE: ['chr21:42412041: model error']
CHECK LINE: ['chr21:43311525: model error']
CHECK LINE: ['chr21:43758543: model error']
CHECK LINE: ['chr21:44773681: model error']
CHECK LINE: ['chr21:46325394: model error']
CHECK LINE: ['chr22:17920284: fitting error']
CHECK LINE: ['chr22:19431486: model error']
CHECK LINE: ['chr22:19986583: fitting error']
CHECK LINE: ['chr22:20510464: model error']
CHECK LINE: ['chr22:23245163: model error']
CHECK LINE: ['chr22:29813302: model error']
CHECK LINE: ['chr22:30202811: model error']
CHECK LINE: ['chr22:30420763: model error']
CHECK LINE: ['chr22:31347557: model error']
CHECK LINE: ['chr22:31857503: model error']
CHECK LINE: ['chr22:35627563: model error']
CHECK LINE: ['chr22:36466209: model error']
CHECK LINE: ['chr22:37328303: fitting error']
CHECK LINE: ['chr22:37534165: fitting error']
CHECK LINE: ['chr22:37601737: fitting error']
CHECK LINE: ['chr22:38180953: model error']
CHECK LINE: ['chr22:39205639: model error']
CHECK LINE: ['chr22:40370894: fitting error']
CHECK LINE: ['chr22:41444507: model error']
CHECK LINE: ['chr22:42720050: fitting error']
CHECK LINE: ['chr22:43152473: model error']
CHECK LINE: ['chr22:45544692: model error']
CHECK LINE: ['chr22:45916907: fitting error']
CHECK LINE: ['chr22:46336323: fitting error']
CHECK LINE: ['chr22:46547487: model error']
CHECK LINE: ['chr22:46830473: model error']
CHECK LINE: ['chr22:50158189: fitting error']
CHECK LINE: ['chr22:50622239: fitting error']
CHECK LINE: ['chr3:4984261: model error']
CHECK LINE: ['chr3:8691000: model error']
CHECK LINE: ['chr3:9351960: model error']
CHECK LINE: ['chr3:10142023: model error']
CHECK LINE: ['chr3:10249322: fitting error']
CHECK LINE: ['chr3:11770655: fitting error']
CHECK LINE: ['chr3:12676471: fitting error']
CHECK LINE: ['chr3:13112428: model error']
CHECK LINE: ['chr3:18331198: model error']
CHECK LINE: ['chr3:24019432: model error']
CHECK LINE: ['chr3:24598906: model error']
CHECK LINE: ['chr3:31649711: model error']
CHECK LINE: ['chr3:32392704: model error']
CHECK LINE: ['chr3:36944124: fitting error']
CHECK LINE: ['chr3:40971833: model error']
CHECK LINE: ['chr3:43866667: model error']
CHECK LINE: ['chr3:43997026: model error']
CHECK LINE: ['chr3:45979653: model error']
CHECK LINE: ['chr3:47163198: model error']
CHECK LINE: ['chr3:48427108: model error']
CHECK LINE: ['chr3:50328649: model error']
CHECK LINE: ['chr3:52277694: model error']
CHECK LINE: ['chr3:53046608: model error']
CHECK LINE: ['chr3:56682558: fitting error']
CHECK LINE: ['chr3:58010544: fitting error']
CHECK LINE: ['chr3:63817403: fitting error']
CHECK LINE: ['chr3:66367356: model error']
CHECK LINE: ['chr3:79314578: model error']
CHECK LINE: ['chr3:100400442: model error']
CHECK LINE: ['chr3:101924924: model error']
CHECK LINE: ['chr3:102174683: model error']
CHECK LINE: ['chr3:105367940: model error']
CHECK LINE: ['chr3:107524848: model error']
CHECK LINE: ['chr3:112752373: model error']
CHECK LINE: ['chr3:112801847: model error']
CHECK LINE: ['chr3:113699062: fitting error']
CHECK LINE: ['chr3:121979522: model error']
CHECK LINE: ['chr3:125164027: model error']
CHECK LINE: ['chr3:126984246: model error']
CHECK LINE: ['chr3:129674294: model error']
CHECK LINE: ['chr3:132137179: model error']
CHECK LINE: ['chr3:138629517: model error']
CHECK LINE: ['chr3:141431960: model error']
CHECK LINE: ['chr3:142446078: model error']
CHECK LINE: ['chr3:149300331: model error']
CHECK LINE: ['chr3:149388901: model error']
CHECK LINE: ['chr3:150408922: fitting error']
CHECK LINE: ['chr3:152942348: model error']
CHECK LINE: ['chr3:158772028: model error']
CHECK LINE: ['chr3:159881974: fitting error']
CHECK LINE: ['chr3:161421128: model error']
CHECK LINE: ['chr3:170356893: model error']
CHECK LINE: ['chr3:172153504: model error']
CHECK LINE: ['chr3:174860019: model error']

Number of features considered: 3083
SRR13772353_EMG

CHECK LINE: ['chr1:149847302: model error']
CHECK LINE: ['chr1:151680892: model error']
CHECK LINE: ['chr12:45233041: fitting error']
CHECK LINE: ['chr14:53947013: fitting error']
CHECK LINE: ['chr17:3049015: model error']
CHECK LINE: ['chr18:3246234: fitting error']
CHECK LINE: ['chr19:3369654: model error']
CHECK LINE: ['chr2:45650050: model error']
CHECK LINE: ['chr2:121075328: model error']
CHECK LINE: ['chr2:218733759: fitting error']
CHECK LINE: ['chr2:237673700: fitting error']
CHECK LINE: ['chr3:12188166: model error']
CHECK LINE: ['chr3:138633880: model error']
CHECK LINE: ['chr6:108592766: model error']
CHECK LINE: ['chr7:6635481: fitting error']
CHECK LINE: ['chr7:12210619: model error']
CHECK LINE: ['chr7:16754428: model error']
CHECK LINE: ['chr7:91266394: model error']
CHECK LINE: ['chr7:106660063: model error']
CHECK LINE: ['chr8:98940128: model error']
CHECK LINE: ['chr9:79572578: model error']
CHECK LINE: ['chr9:111693805: model error']
CHECK LINE: ['chr9:113341856: model error']
CHECK LINE: ['chr9:114619526: model error']
CHECK LINE: ['chr9:115591791: model error']
CHECK LINE: ['chr9:128120516: model error']

Number of features considered: 4476
Number of features considered: 13

CHECK LINE: ['chr1:149847302: fitting error']
CHECK LINE: ['chr19:3369654: fitting error']
CHECK LINE: ['chr7:12210619: fitting error']
CHECK LINE: ['chr9:115591791: fitting error']
CHECK LINE: ['chr17:3049015: fitting error']
CHECK LINE: ['chr2:45650050: fitting error']
CHECK LINE: ['chr2:237673700: fitting error']
CHECK LINE: ['chr6:108592766: fitting error']
CHECK LINE: ['chr7:16754428: fitting error']
CHECK LINE: ['chr8:98940128: fitting error']
CHECK LINE: ['chr9:128120516: fitting error']
CHECK LINE: ['chr12:45233041: fitting error']
CHECK LINE: ['chr18:3246234: fitting error']

## Getting conensus calls from multiple samples
* Use a weighted average where the call is weighted by the amount of NON-background coverage

In [54]:
print(df_dict[prefix].columns)

Index(['chrom', 'start', 'stop', 'strand', 'gene', 'mL_mean', 'mL_stdev',
       'sL_mean', 'sL_stdev', 'tI_mean', 'tI_stdev', 'w_LI_mean', 'w_LI_stdev',
       'w_B_mean', 'w_B_stdev', 'mL_a_mean', 'mL_a_stdev', 'sL_a_mean',
       'sL_a_stdev', 'tI_a_mean', 'tI_a_stdev', 'w_aLI_mean', 'w_aLI_stdev',
       'w_aB_mean', 'w_aB_stdev', '0.75_perc_pos', '0.75_perc_neg',
       '0.8_perc_pos', '0.8_perc_neg', '0.85_perc_pos', '0.85_perc_neg',
       '0.9_perc_pos', '0.9_perc_neg', '0.95_perc_pos', '0.95_perc_neg',
       'pos_cov', 'neg_cov', 'elbo_lrange', 'elbo_urange', 'fit_time_min'],
      dtype='object')

In [81]:
# Combine all dataframes in the dictionary
combined = pd.concat(
    [df.assign(source=key) for key, df in df_dict.items()],
    ignore_index=True
)
combined["pos_cov_nob"] = (1 - combined["w_B_mean"])* combined['pos_cov']
combined["neg_cov_nob"] = abs((1 - combined["w_aB_mean"])* combined['neg_cov'])

def compute_weighted(group):
    """
    Get the weighted average of the end. Here the end is based on the 95 percentile.
    The coverage (not including background) is used to weight the calls where the calls with higher coverage are weighted higher.
    """
    total_pos_cov = group['pos_cov_nob'].sum()
    total_neg_cov = group['neg_cov_nob'].sum()
    
    # Weighted averages (protect against division by zero)
    weighted_pos = (group['0.95_perc_pos'] * group['pos_cov_nob']).sum() / total_pos_cov if total_pos_cov > 0 else float('nan')
    weighted_neg = (group['0.95_perc_neg'] * group['neg_cov_nob']).sum() / total_neg_cov if total_neg_cov > 0 else float('nan')
    
    # Number of unique dataframes that had this gene
    num_dfs = group['source'].nunique()
    
    # Average coverage
    avg_pos_cov = group['pos_cov_nob'].mean()
    avg_neg_cov = group['neg_cov_nob'].mean()

    return pd.Series({
        'weighted_0.95_perc_pos': weighted_pos,
        'weighted_0.95_perc_neg': weighted_neg,
        'num_dataframes': num_dfs,
        'avg_pos_cov_nob': avg_pos_cov,
        'avg_neg_cov_nob': avg_neg_cov
    })

consensus = combined.groupby('gene').apply(compute_weighted, include_groups=False).reset_index()
consensus.iloc[0:3,]

,gene,weighted_0.95_perc_pos,weighted_0.95_perc_neg,num_dataframes,avg_pos_cov_nob,avg_neg_cov_nob
0,chr10:100311438,683.000000,205.000000,1.0,23.40,13.02
1,chr10:100346521,1385.302398,875.057179,2.0,626.26,510.68
2,chr10:100348799,NaN,1414.929936,2.0,0.00,50.24

## I want to look at details of my calls
The FitParse class produces a dataframe that stores all of the relevant values: 
1. Original annotation file inputs: 'chrom', 'start', 'stop', 'strand', 'gene',
2. Final mean and standard deviations of the posterior position/sigma values (in bp and if position relative to start:
    *  Sense (Positive if ENhancer): 'mL_mean', 'mL_stdev', 'sL_mean', 'sL_stdev', 'tI_mean', 'tI_stdev'
    *  Antisense (Negative if Enhancer): 'mL_a_mean', 'mL_a_stdev', 'sL_a_mean', 'sL_a_stdev', 'tI_a_mean', 'tI_a_stdev'
3. Final mean standard deviations of the weights of each part of the model (LI and B for ET=False and LI, E, T, and B for ET=True)
    * Sense (Positive if enhancer): 'w_LI_mean', 'w_LI_stdev', 'w_B_mean', 'w_B_stdev'
    * Antisense (Negative if enhancer): 'w_aLI_mean', 'w_aLI_stdev', 'w_aB_mean', 'w_aB_stdev'
4. Percentile Positions (in bp relative to start, if _neg then to left of start)
    * _pos = sense/positive strand, _neg = antisense/negative strand
    * '0.75_perc_pos', '0.75_perc_neg','0.8_perc_pos', '0.8_perc_neg', '0.85_perc_pos', '0.85_perc_neg',
       '0.9_perc_pos', '0.9_perc_neg', '0.95_perc_pos', '0.95_perc_neg'
5. Coverage: Number of reads in the full padded region on positive and negative strand
    * 'pos_cov', 'neg_cov',
6. Elbow Loss Range (Lower and Upper)
    * 'elbo_lrange', 'elbo_urange', 
8. Time used to fit the model
    * 'fit_time_min'

In [85]:
print(df_dict[prefix].columns)

Index(['chrom', 'start', 'stop', 'strand', 'gene', 'mL_mean', 'mL_stdev',
       'sL_mean', 'sL_stdev', 'tI_mean', 'tI_stdev', 'w_LI_mean', 'w_LI_stdev',
       'w_B_mean', 'w_B_stdev', 'mL_a_mean', 'mL_a_stdev', 'sL_a_mean',
       'sL_a_stdev', 'tI_a_mean', 'tI_a_stdev', 'w_aLI_mean', 'w_aLI_stdev',
       'w_aB_mean', 'w_aB_stdev', '0.75_perc_pos', '0.75_perc_neg',
       '0.8_perc_pos', '0.8_perc_neg', '0.85_perc_pos', '0.85_perc_neg',
       '0.9_perc_pos', '0.9_perc_neg', '0.95_perc_pos', '0.95_perc_neg',
       'pos_cov', 'neg_cov', 'elbo_lrange', 'elbo_urange', 'fit_time_min',
       'pos_cov_nob', 'neg_cov_nob'],
      dtype='object')

In [86]:
df_dict[prefix].iloc[0:3,]

,chrom,start,stop,strand,gene,mL_mean,mL_stdev,sL_mean,sL_stdev,tI_mean,...,0.9_perc_neg,0.95_perc_pos,0.95_perc_neg,pos_cov,neg_cov,elbo_lrange,elbo_urange,fit_time_min,pos_cov_nob,neg_cov_nob
chr10:100346521,chr10,100346521,100346721,1,chr10:100346521,32.74,18.74,404.15,19.19,114.39,...,749,841,940,280,-848,8434.010605,10146.755816,4.17,274.4,780.16
chr10:100348799,chr10,100348799,100348999,1,chr10:100348799,3.89,70.24,68.29,74.04,50.74,...,173,200,212,2048,-36,17746.375715,23787.155931,8.03,0.0,1.08
chr10:100997734,chr10,100997734,100997934,1,chr10:100997734,32.46,28.45,280.73,26.35,75.47,...,608,588,778,1750,-2241,34046.224232,44009.411948,13.68,140.0,112.05